spring:
  application:
    name: design
  datasource:
    url: jdbc:mysql://localhost:3306/noob
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: young
    password: 020129yjc
#写你自己的数据库
  thymeleaf:
    cache: false
server:
  servlet:
    session:
      timeout: 30m